const PROFILE_HOST = '127.0.0.1';
const PROFILE_PORT = '8123';
const STORE_HOST = '127.0.0.1';
const STORE_PORT = '8124';
module.exports = {
	PROFILE_HOST: PROFILE_HOST,
	PROFILE_PORT: PROFILE_PORT,
	STORE_HOST: STORE_HOST,
	STORE_PORT: STORE_PORT
};
